[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "/bin/sh -c \"cd /rails && bundle exec rails db:prepare\""
startCommand = "/rails/bin/start-server"
healthcheckPath = "/up"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
